name: alura-php-mysql
services:
  web:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    ports:
      - name: web
        target: 80
        published: "8080"
        protocol: tcp
        app_protocol: http
        mode: host
  database:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8;'
    image: mysql:8
    environment:
      MYSQL_DATABASE: serenatto
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
      - type: bind
        source: db.sql
        target: /docker-entrypoint-initdb.d/db.sql
volumes:
  mysql_data:
